### PR TITLE
[Trusted Types] Legacy converting more violations sourced from setHtml wrapper function

### PR DESCRIPTION
**Pull request by youssef-attia**
## What is the purpose of this pull request?

PR to legacy convert certain violations specifically coming from setHtml wrapper function to help with making CKEditor [Trusted Types](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) compatible.

### CODE REVIEW

**Review by eozmen410 — APPROVED** [review]
LGTM! Thanks :)

**Comment by eozmen410** [comment]
Before I merge, did we run the tests for this change?

**Comment by youssef-attia** [comment]
image
All failing tests pass when opening them and running them in another tab. Note: the time increase here is in part due to some debugging breakpoints.

**Comment by youssef-attia** [comment]
image
No failures

**Comment by youssef-attia** [comment]
image
All failing tests pass when opening them and running them in another tab.

**Comment by youssef-attia** [comment]
image
All failing tests pass when opening them and running them in another tab.

**Pull request merged**
